name: "Asana link with commit"
description: "Link and more info Github commit with an Asana Task"
inputs:
  asana-pat:
    description: "Asana Private Access Token."
    required: true
  asana-project:
    description: "Asana project guid."
    required: true
branding:
  icon: "at-sign"
  color: "gray-dark"
runs:
  using: "node16"
  main: "dist/index.js"
