name: AsanaTaskWithComment

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  linkAsana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Link commit with Asana
        uses: michailElsikora/asana-commit-inegration@2.0.1
        with:
          asana-pat: ${{ secrets.ASANA_PAT  }}
          asana-project: ${{ secrets.ASANA_PROJECT }}
