name: AsanaTaskWithComment

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  linkAsana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Link commit with Asana
        uses: michailElsikora/asana-commit-inegration@2.0.7
        with:
          asana-pat: ${{ secrets.ASANA_PAT  }}
          asana-project: ${{ secrets.ASANA_PROJECT }}
