name: AsanaTaskLink

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  linkAsana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Link commit with Asana
        uses: michailElsikora/asana-commit-inegration@v1.0
        with:
          asana-pat: 1/1202249710596714:3f8af5ba604d4f3a2bdb38188681c050
